apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cv9xj1p9v-dotnet-basic 
  janus-idp.io/tekton: cv9xj1p9v-dotnet-basic
  backstage.io/kubernetes-id: cv9xj1p9v-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cv9xj1p9v-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml