apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cv9xj1p9v-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/cv9xj1p9v-dotnet-basic